---
title: The Red Bag
timezone: EST
collections:
  questions:
    title: Questions
    output: false
  intro:
    title: Intro
    output: false
  conclusion:
    title: conclusion
    output: false
  uploads:
    title: Uploads
    output: true
email: aiden@thewanderingsocialites.com
description: What's in The Red Bag
baseurl: ''
url: http://theredbag.us
github_username: popcornindiana
