---
title: The Red Bag
tagline: Popcorn Indiana
timezone: EST
collections:
  intro:
    title: Intro
    output: false
  posts:
    title: Posts
    output: true
  questions:
    title: Questions
    output: false
  uploads:
    title: Uploads
    output: true
  conclusion:
    title: conclusion
    output: false
email: aiden@thewanderingsocialites.com
description: What's in The Red Bag
baseurl: ''
url: http://theredbag.us
github_username: popcornindiana
